nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando se nome...')
print(f'Seu nome em letras maiúsculas é {nome.upper()}')
print(f'Seu nome completo em letras minúsculas é {nome.lower()}')
print('Seu nome tem ao todo {} letras'.format(len(nome) - nome.count(' ')))
separa = nome.split()
print(f'Seu primeiro nome é {separa[0]}, e ele tem {len(separa[0])} letras.')
